### ISSUE TITLE
Direction request fail

### ISSUE THREAD

**Issue by Monacr** [yingfc/cse403#17]
When I click GO TO I get this notification.

Directions request failed.MapsRequestError: DIRECTIONS_ROUTE: REQUEST_DENIED: The webpage is not allowed to use the directions service.

**Comment by yingfc** [comment]
Have you enabled the location-sharing service on your browser? it is needed to get your current location.
https://github.com/yingfc/cse403#frontend-npm-server

**Comment by yingfc** [comment]
Closing this issue as getting no response from the reporter. Such an error should be resolved by enabling the location-sharing service on the browser.
